apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
    name: where-for-dinner
spec:
    serviceAccountName: default
    packageRef:
        refName: where-for-dinner.my-apps.tap
        versionSelection:
            constraints: 20240131070222.0.0+build.02e9424
    values:
        - secretRef:
            name: where-for-dinner
