apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-availability.my-apps.tap.20240131082512.0.0+build.02e9424
spec:
  refName: where-for-dinner-availability.my-apps.tap
  version: 20240131082512.0.0+build.02e9424
  releaseNotes: |
    Release v20240131082512.0.0+build.02e9424 of package where-for-dinner-availability.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-31-01-2024-06-28-11-369045833/where-for-dinner-availability-my-apps-bundle@sha256:0525af0ab6e34045e554b1005e6c203b461d1aa9d6d41658d6b19825574e9e08
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

