apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-notify.my-apps.tap.20240201165442.0.0+build.c5ac160
spec:
  refName: where-for-dinner-notify.my-apps.tap
  version: 20240201165442.0.0+build.c5ac160
  releaseNotes: |
    Release v20240201165442.0.0+build.c5ac160 of package where-for-dinner-notify.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-31-01-2024-06-28-11-369045833/where-for-dinner-notify-my-apps-bundle@sha256:d2a716e285029b1c4d054d2695eae7806554ff464ec0dc4e7517566479690a48
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

